# Generated by Django 5.0.6 on 2024-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='default/fon.png', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default/profile.png', upload_to='profile_images/'),
        ),
    ]
